JDBC.username=root
JDBC.password=362203
JDBC.driver=com.mysql.cj.jdbc.Driver
#最大数据库连接数
JDBC.maxActive= 15
#最小的空闲连接
JDBC.minIdle = 5
#初始化的时候的连接数
JDBC.initialSize = 3
#与数据库连接的最大等待时长
JDBC.maxWait = 10000
#空闲检测
JDBC.testWhileIdle = true
#检测时候的SQL语句，单纯为了测试
JDBC.validationQuery = SELECT 1
#检测间隔
JDBC.timeBetweenEvictionRunsMillis = 5000
#是否移除不活跃连接
JDBC.removeAbandoned = true
#判定为不活跃连接的时间，单位为秒
JDBC.removeAbandonedTimeout = 30
JDBC.filters = stat

Jedis.password = 578616559
Jedis.port = 6379
Jedis.database = 0
Jedis.timeout = 1000
Jedis.maxIdle = 50
Jedis.maxTotal = 200
Jedis.minIdle = 50